import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/css/ReactHook.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="/img/logo.png"/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          React hook
        </h1>
        <div className="flex">
          <p className={styles.description}>
            <Link href="/hook/usestate">useState</Link>
          </p>
          <p className={styles.description}>
            <Link href="/hook/useeffect">useEffect</Link>
          </p>
        </div>
        <div className="flex">
          <p className={styles.description}>
            <Link href="/">TOP</Link>
          </p>
        </div>
      </main>
    </div>
  )
}